### ISSUE TITLE
NameError: name 'cvRfHierarchyT' is not defined

### ISSUE THREAD

**Issue by arilwan** [SalilVishnuKapur/Predicting-Transportation-Modes-of-GPS-Trajectories#4]
@SalilVishnuKapur 
Can't figure out where this variable is defined in the Pointfeatures.py script, but getting this error:
```
Traceback (most recent call last):
  File "PointFeatures.py", line 163, in <module>
    arrRfH = [np.mean(cvRfHierarchyT[0]), np.mean(cvRfHierarchyT[1]), np.mean(cvRfHierarchyT[2]), np.mean(cvRfHierarchyT[3]), np.mean(cvRfHierarchyT[4]), np.mean(cvRfHierarchyT[5])]
NameError: name 'cvRfHierarchyT' is not defined
```

**Comment by SalilVishnuKapur** [comment]
Line 578 cvRfHierarchyT = transformer(cvRfHierarchy[0])
https://github.com/SalilVishnuKapur/Predicting-Transportation-Modes-of-GPS-Trajectories/blob/master/PointFeatures.py

Let me know if it helps?

**Comment by arilwan** [comment]
@SalilVishnuKapur 

So it appears `cvRfHierarchyT` is used before its declaration?
```
$python PointFeatures.py
Traceback (most recent call last):
  File "PointFeatures.py", line 163, in <module>
    arrRfH = [np.mean(cvRfHierarchyT[0]), np.mean(cvRfHierarchyT[1]), np.mean(cvRfHierarchyT[2]), np.mean(cvRfHierarchyT[3]), np.mean(cvRfHierarchyT[4]), np.mean(cvRfHierarchyT[5])]
NameError: name 'cvRfHierarchyT' is not defined

```
PointFeatures.py script issues NameError. (Line 163)

**Comment by SalilVishnuKapur** [comment]
I believe this bug came because of the more class oriented project modification that I had planned to do. But unfortunately, I couldn't take out time to finish that. But in few days I will surely get this done with even better developer documentation.
